### ISSUE TITLE
How about to add localization support?

### ISSUE THREAD

**Issue by 318cyz** [Sub-Bubble/CharmsBarReloaded#3]
Could you please add localization support?

If you need, I can do the zh-cn translate.

**Comment by Sub-Bubble** [comment]
Hello, thanks for the suggestion!

This will be added in the first beta version, which is currently in the works. Unfortunately, it will take some time due to the fact that the beta requires a lot of work currently.

As for zh-cn translation, you can commit it to the project once this feature is released. I will notify you once that happens.

**Comment by Sub-Bubble** [comment]
Hello, an update about localization support - it is currently finished in [beta branch](https://github.com/Sub-Bubble/CharmsBarReloaded/tree/beta).

You can create a pull request for your translation for it to be added into an update, i have also provided you a link to an example English (US) translation file [here](https://github.com/Sub-Bubble/CharmsBarReloaded/blob/beta/src/CharmsBarReloaded.Config/lang/en-us.json) to get you started.

b1.0 will soon come out, we are currently testing for bugs and if none are found, it will be merged into master branch.

**Comment by 318cyz** [comment]
Thanks. I will do it as fast as possible.

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
